export const ORDRE_ARCS = [
  'Romance Dawn',
  'Orange',
  'Sirop',
  'Baratie',
  'Arlong Park',
  'Loguetown',
  'Drum',
  'Alabasta',
  'Jaya',
  'Skypiea',
  'Long Ring Long Land',
  'Water 7',
  'Enies Lobby',
  'Thriller Bark',
  'Sabaody',
  'Amazon Lily',
  'Impel Down',
  'Marineford',
  'Île des Hommes-Poissons',
  'Punk Hazard',
  'Dressrosa',
  'Zou',
  'Whole Cake Island',
  'Wano',
];
